version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: grunt
    versions:
    - 1.4.0
  - dependency-name: node-red
    versions:
    - 1.2.8
    - 1.2.9
    - 1.3.1
    - 1.3.2
    - 1.3.3
  - dependency-name: "@nlpjs/basic"
    versions:
    - 4.19.8
    - 4.20.0
    - 4.21.0
    - 4.21.2
    - 4.21.3
    - 4.22.0
  - dependency-name: grunt-nr-locales-htmllint
    versions:
    - 1.2.1
  - dependency-name: "@nlpjs/qna-importer"
    versions:
    - 4.21.1
  - dependency-name: node-red-node-test-helper
    versions:
    - 0.2.6
    - 0.2.7
  - dependency-name: mocha
    versions:
    - 8.3.0
